#*****************************************************************************#
#    Copyright (C) 2026 Julian Xhokaxhiu                                      #
#                                                                             #
#    This file is part of timewarp                                            #
#                                                                             #
#    timewarp is free software: you can redistribute it and\or modify         #
#    it under the terms of the GNU General Public License as published by     #
#    the Free Software Foundation, either version 3 of the License            #
#                                                                             #
#    timewarp is distributed in the hope that it will be useful,              #
#    but WITHOUT ANY WARRANTY; without even the implied warranty of           #
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the            #
#    GNU General Public License for more details.                             #
#*****************************************************************************#

name: timewarp

run-name: 0.1.0.${{ github.run_number }}

on:
  workflow_dispatch:
  push:
    branches:
    - master
    tags:
    - "*"
  pull_request:
    branches:
    - master

env:
  _IS_BUILD_CANARY: false
  _IS_GITHUB_RELEASE: false
  _RELEASE_NAME: timewarp
  _RELEASE_VERSION: v0
  _RELEASE_CONFIGURATION: Release
  _BUILD_BRANCH: "${{ github.ref }}"
  _CHANGELOG_VERSION: "0"
  # GIT: Fix reporting from stderr to stdout
  GIT_REDIRECT_STDERR: 2>&1


jobs:
  build:
    name: Build (${{ matrix._RELEASE_ARCHITECTURE }})
    runs-on: windows-latest
    timeout-minutes: 1440
    strategy:
      matrix:
        _RELEASE_ARCHITECTURE: [x86, x64]
    steps:
      - name: Set Git Config
        run: |
          git config --global core.autocrlf false
          git config --global core.filemode false
          git config --global core.longpaths true
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Prepare Environment
        run: ".github/workflows/prepare.ps1"
        shell: pwsh
        env:
          _BUILD_VERSION: "0.1.0.${{ github.run_number }}"
      - name: Build
        run: ".github/workflows/build.ps1"
        shell: pwsh
        env:
          GITHUB_PACKAGES_PAT: ${{ secrets.GITHUB_TOKEN }}
          _RELEASE_ARCHITECTURE: ${{ matrix._RELEASE_ARCHITECTURE }}

      - name: Upload vcpkg build logs
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: vcpkg-logs
          path: ${{ github.workspace }}/vcpkg/buildtrees/**/*.log

      - name: Upload build artifact
        if: success()
        uses: actions/upload-artifact@v4.0.0
        with:
          name: "${{ env._RELEASE_NAME }}-${{ env._RELEASE_VERSION }}-${{ matrix._RELEASE_ARCHITECTURE }}"
          path: ".dist/*.zip"

  post-build:
    name: Release
    runs-on: windows-latest
    needs: build
    if: success()
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Prepare Environment
        run: ".github/workflows/prepare.ps1"
        shell: pwsh
        env:
          _BUILD_VERSION: "0.1.0.${{ github.run_number }}"
      - name: Download all build artifacts
        if: env._IS_GITHUB_RELEASE == 'true'
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true
      - name: VirusTotal Scan
        id: vt-scan
        if: env._IS_GITHUB_RELEASE == 'true' && success()
        uses: crazy-max/ghaction-virustotal@v4
        with:
          vt_api_key: ${{ secrets._VT_API_KEY }}
          files: "*.zip"
      - name: Parse VirusTotal Results
        id: vt-res
        if: env._IS_GITHUB_RELEASE == 'true' && success()
        uses: actions/github-script@v7
        with:
          result-encoding: string
          script: |
            let ret = `${{ steps.vt-scan.outputs.analysis }}`;

            ret = '- ' + ret
            .replaceAll('.dist/','')
            .replaceAll('=h', ': h')
            .replaceAll(',', "\n- ");

            console.log('Results:');
            console.log(ret);

            return ret;
      - name: Move canary tag to this commit
        uses: richardsimko/update-tag@v1
        if: env._IS_GITHUB_RELEASE == 'true' && env._IS_BUILD_CANARY == 'true' && success()
        with:
          tag_name: canary
      - name: Publish Canary release
        uses: ncipollo/release-action@v1
        if: env._IS_GITHUB_RELEASE == 'true' && env._IS_BUILD_CANARY == 'true' && success()
        with:
          artifacts: "*.zip"
          allowUpdates: true
          generateReleaseNotes: true
          prerelease: true
          removeArtifacts: true
          tag: canary
          name: "${{ env._RELEASE_NAME }}-${{ env._RELEASE_VERSION }}"
          body: |
            See https://github.com/julianxhokaxhiu/FFNx/blob/master/Changelog.md#next

            This is a canary build. Please be aware it may be prone to crashing and is NOT tested by anyone. Use this build AT YOUR OWN RISK!

            ğŸ›¡ï¸ **VirusTotal analysis:**
            ${{ steps.vt-res.outputs.result }}
      - name: Publish Stable release
        uses: ncipollo/release-action@v1
        if: env._IS_GITHUB_RELEASE == 'true' && env._IS_BUILD_CANARY == 'false' && success()
        with:
          artifacts: "*.zip"
          generateReleaseNotes: true
          makeLatest: true
          removeArtifacts: true
          name: "${{ env._RELEASE_NAME }}-${{ env._RELEASE_VERSION }}"
          body: |
            See https://github.com/julianxhokaxhiu/FFNx/blob/master/Changelog.md#${{ env._CHANGELOG_VERSION }}

            ğŸ›¡ï¸ **VirusTotal analysis:**
            ${{ steps.vt-res.outputs.result }}
      - name: Cleanup previous release workflows
        uses: Mattraks/delete-workflow-runs@v2
        if: env._IS_GITHUB_RELEASE == 'true' && env._IS_BUILD_CANARY == 'false' && success()
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 1
          keep_minimum_runs: 1
          delete_run_by_conclusion_pattern: >-
            ${{
              !contains(github.event.inputs.delete_run_by_name_pattern, '0.1.0')
              && github.event.inputs.delete_run_by_name_pattern
            }}
